### ISSUE TITLE
tcpresolver.h _socket should be of type SOCKET

### ISSUE THREAD

**Issue by leleftheriades** [fantastory/AMQP-CPP.nuget#1]
When building on x64, assigning the SOCKET result of WSASocket which is a pointer to the 32bit value int _socket, [will truncate it](https://msdn.microsoft.com/en-us/library/3b2e7499.aspx)

Converting it to a pointer will have the side-effect that checks/comparisons for invalid socket should be against INVALID_SOCKET (an unsigned value)

Additionally errors from windows sockets are optained by a call to WSAGetLastError() instead of errno.

strerror(errno) can be replaced by:

```
std::string getLastSocketError(){
	std::string error;
	char *s = nullptr;
	FormatMessageA(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS, 
				   NULL, WSAGetLastError(),
				   MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
				   (LPSTR)&s, 0, NULL);
	error = s;
	LocalFree(s);
	return error;
}
```

**Comment by fantastory** [comment]
I will check it with 64 build, and thanks for the WSAGetLastError reminder.

Are you interested in windows build?
I will rather use boost implementation which was included in removed examples.

**Comment by fantastory** [comment]
#f0a731afb272a01a9900ca3266bec1e536bce1a5
